language: c

branches:
  only:
  - master

os : osx
arch : amd64
osx_image: xcode12.1
script:
  - mkdir build
  - cd build
  - cmake .. -GXcode -DCMAKE_SYSTEM_NAME=iOS
  - cmake --build . --config Release
  - make test



# matrix:
#   include:
#     - os: linux
#       arch: amd64
#       compiler: gcc
#       env: 
#         - buildtype=-DCMAKE_BUILD_TYPE=Debug
#         - sanitizer=CFLAGS="-fsanitize=address"

#     - os: linux
#       arch: amd64
#       compiler: clang
#       env: 
#         - buildtype=-DCMAKE_BUILD_TYPE=Release
#         - sanitizer=CFLAGS="-fsanitize=address"

#     - os: linux
#       addons:
#         apt:
#           packages:
#             - binutils-mingw-w64
#             - gcc-mingw-w64
#       compiler: x86_64-w64-mingw32-gcc
#       env: 
#         - CROSS=1 
#         - toolchain=-DCMAKE_TOOLCHAIN_FILE=./x86_64-windows-mingw64.cmake
#         - buildtype=-DCMAKE_BUILD_TYPE=Release

#     - os: osx
#       arch: amd64
#       compiler: clang
#       env: 
#         - sanitizer=CFLAGS="-fsanitize=memory"

#     - os: osx
#       arch: amd64
#       osx_image: xcode11.1
#       compiler: clang
#       env: 
#         - buildtype=-DCMAKE_BUILD_TYPE=Release
#         - sanitizer=CFLAGS="-fsanitize=memory"

#     - os: osx
#       arch: amd64
#       osx_image: xcode11.1
#       compiler: clang
#       env: 
#         - buildtype=-DCMAKE_BUILD_TYPE=Release
#         - sanitizer=-DUSE_MSAN=ON

# script:
#   - cmake $toolchain $buildtype $sanitizer .
#   - make
#   - if [ -z "$CROSS" ]; then make test; fi
#   - cat /Users/travis/build/piggypiggy/travis-test/build/CMakeFiles/CMakeOutput.log
#   - cat /Users/travis/build/piggypiggy/travis-test/build/CMakeFiles/CMakeError.log
